on:
  push:
    tags:
      - "v*"
name: Upload Binary to Release

jobs:
  build:
    permissions: write-all
    name: Upload Binary to Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Nim Environment
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '2.0.2' # default is 'stable'
          # repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
      - name: Build Binaries
        run: |
          mkdir -p bin
          nim c -d:ssl -d:release --opt:size --cpu:amd64 -o:bin/povi-amd64.bin src/povi
          nim c -d:ssl -d:mingw -d:release --opt:size -o:bin/povi-amd64.exe --cpu:amd64 src/povi

      - name: Upload Binaries to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            bin/povi-amd64.bin
            bin/povi-amd64.exe
